#!/bin/bash  -e

echo 1 $diretorio_facil
#Carrega as variáveis do arquivo ini local
. local-facil.ini

echo 2 $diretorio_facil

if [ -z "$1" ]
then
	echo Olá mundo!
	echo Digite: facil ajuda 
else
	bash $diretorio_facil/$1 $2
fi
