#!/bin/bash  -e

#Carrega as variáveis do arquivo ini local
. local-facil.ini

#Se tentar iniciar com 'facil', erro
if [[ $1 == "iniciar" ]]
then 
	echo "Para iniciar digite 'bash iniciar' dentro do diretorio $diretorio_facil" 
	exit 1
fi

#Se não definir variáveis, envia mensagens
if [ -z "$1" ]
then
	#Envia mensagens
	echo Olá mundo!
	echo Digite: facil ajuda 
else
	
	#Envia variáveis para o script a ser chamado
	export diretorio_facil
	
	#Executa comando
	
	set -xve
	bash $diretorio_facil/$1/$2.txt
	set +xve
fi

#Manter o shell BASH, independentemente da chamada do Shell (sh ou dash) 
if [ -z "$BASH_VERSION" ]
then
    exec bash "$0" "$@"
fi