#!/bin/bash -xv -e

#Define os caminhos correntes da instalação local
caminho_iniciar=$PWD/$0
diretorio_facil="${caminho_iniciar/\/iniciar/''}"

#Dá permissão de execução para o arquivo principal 'facil'
chmod +x $diretorio_facil/facil

#Verifica se existe variável $PATH definida no arquivo
existe_path=$(grep -c "PATH=" $HOME/.bashrc)

#Faz backup do arquivo antes de modificar
data_hora=$(date +%Y-%m-%d-%H-%M-%S)
cp $HOME/.bashrc $HOME/.bashrc.$data_hora.bak

#Se existir a variável $PATH, ajusta, senão, cria
if [[ $existe_path -ge 1 ]]; then
	sed -i 's;^PATH=.*;PATH='$diretorio_facil:"$PATH"';' $HOME/.bashrc
else
	echo PATH=$diretorio_facil:"$PATH" >> $HOME/.bashrc
fi

#Recarrega o shell para considerar o novo $PATH
exec bash
